name: build

on:
    schedule:
        - cron: "01 23 * * *"

env:
    DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
    DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
    ET_REPO_PATH: ${{secrets.ET_REPO_PATH}}
    ET_REPO_TOKEN: ${{secrets.ET_REPO_TOKEN}}

jobs:
    # =============== ODOO COMMUNITY ==================
    build-odoo-community-image-17:
        permissions:
            contents: write
        uses: ./.github/workflows/build.yml
        with:
            ref: "17"
            image_tag: "odoo:17"
            version_code: "17.0"
        secrets: inherit

    build-odoo-community-image-16:
        permissions:
            contents: write
        uses: ./.github/workflows/build.yml
        with:
            ref: "16"
            image_tag: "odoo:16"
            version_code: "16.0"
        secrets: inherit

    build-odoo-community-image-15:
        permissions:
            contents: write
        uses: ./.github/workflows/build.yml
        with:
            ref: "15"
            image_tag: "odoo:15"
            version_code: "15.0"
        secrets: inherit

    build-odoo-community-image-14:
        permissions:
            contents: write
        uses: ./.github/workflows/build.yml
        with:
            ref: "14"
            image_tag: "odoo:14"
            version_code: "14.0"
        secrets: inherit

    # =============== ODOO ENTERPRISE ==================
    build-odoo-et-image-17:
        needs: [build-odoo-community-image-17]
        uses: ./.github/workflows/build-et.yml
        with:
            ref: "17"
            image_tag: "odoo-et:17"
            et_workspace_path: ./et-addons
        secrets: inherit

    build-odoo-et-image-16:
        needs: [build-odoo-community-image-16]
        uses: ./.github/workflows/build-et.yml
        with:
            ref: "16"
            image_tag: "odoo-et:16"
            et_workspace_path: ./et-addons
        secrets: inherit

    build-odoo-et-image-15:
        needs: [build-odoo-community-image-15]
        uses: ./.github/workflows/build-et.yml
        with:
            ref: "15"
            image_tag: "odoo-et:15"
            et_workspace_path: ./et-addons
        secrets: inherit

    build-odoo-et-image-14:
        needs: [build-odoo-community-image-14]
        uses: ./.github/workflows/build-et.yml
        with:
            ref: "14"
            image_tag: "odoo-et:14"
            et_workspace_path: ./et-addons
        secrets: inherit
