name: Checkout and build ET image

on:
    workflow_call:
        inputs:
            ref:
                required: true
                type: string
            image_name:
                required: true
                type: string
            image_tag:
                required: true
                type: string
            et_workspace_path:
                required: true
                type: string

jobs:
    build_and_push:
        runs-on: ubuntu-latest
        env:
            package_manage_token: ${{ secrets.MANAGE_GH_PACKAGE_TOKEN }}
            organization: ${{ vars.ORGANIZATION_NAME }}
            repository: ${{ vars.ENTERPRISE_DOCKER_REPOSITORY }}
        steps:
            - name: Checkout Enterprise source
              uses: actions/checkout@v4
              with:
                  repository: ${{ secrets.ET_REPO_PATH }}
                  token: ${{ secrets.ET_REPO_TOKEN }}
                  path: ${{ inputs.et_workspace_path }}
                  ref: ${{ inputs.ref }}
                  fetch-depth: 1

            - name: Login to GitHub container registry
              run: echo "${{ env.package_manage_token }}" | docker login ghcr.io -u ${{ env.organization }} --password-stdin

            - name: Build image
              run: |
                  cd ${{ inputs.et_workspace_path }}
                  docker build . \
                        --tag ghcr.io/${{ env.organization }}/${{ inputs.image_tag }} \
                        --label "org.opencontainers.image.source=https://github.com/${{ env.organization }}/${{ env.repository }}"

            - name: Publish image to GitHub container registry
              run: |
                  docker push ghcr.io/${{ env.organization }}/${{ inputs.image_tag }}

            - uses: actions/checkout@v4

            - name: Remove untagged (old) image from GitHub container registry
              uses: ./.github/actions/delete-untagged-packages
              with:
                  github_token: ${{ env.package_manage_token }}
                  package_name: ${{ inputs.image_name }}
                  organization: ${{ env.organization }}
