name: build

on:
    schedule:
        - cron: "01 23 * * *"
    push:
        branches: [build]

jobs:
    # =============== ODOO COMMUNITY ==================
    build-community:
        strategy:
            matrix:
                ref: [15, 16, 17]
        permissions:
            contents: write
        uses: ./.github/workflows/build-community.yml
        with:
            ref: ${{ matrix.ref }}
            image_name: odoo
            image_tag: odoo:${{ matrix.ref }}
            version_code: ${{ matrix.ref }}.0
        secrets: inherit

    # =============== ODOO ENTERPRISE ==================
    build-enterprise:
        needs: [build-community]
        strategy:
            matrix:
                ref: [15, 16, 17]
                et_workspace_path: ["./et-addons"]
        uses: ./.github/workflows/build-enterprise.yml
        with:
            ref: ${{ matrix.ref }}
            image_name: odoo-ent
            image_tag: odoo-ent:${{ matrix.ref }}
            et_workspace_path: ${{ matrix.et_workspace_path }}
        secrets: inherit
