name: Checkout and build image # reusable workflow

on:
    workflow_call:
        inputs:
            ref:
                required: true
                type: string
            image_tag:
                required: true
                type: string
            version_code:
                required: true
                type: string
        secrets:
            DOCKERHUB_USERNAME:
                required: true
            DOCKERHUB_TOKEN:
                required: true

jobs:
    commit-latest-release:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  ref: ${{ inputs.ref }}
                  fetch-depth: 1

            - name: Get release bash from nightly server
              run: |
                  bash ${{ github.workspace }}/scripts/update-latest-release.sh "${{ inputs.version_code }}" "${{ github.workspace }}/Dockerfile"

            - uses: stefanzweifel/git-auto-commit-action@v5
              with:
                  commit_message: Update latest release in Dockerfile

    build_and_push:
        runs-on: ubuntu-latest
        needs: [commit-latest-release]
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  ref: ${{ inputs.ref }}
                  fetch-depth: 1

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Build & Publish image
              run: |
                  docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/${{ inputs.image_tag }} .
                  docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ inputs.image_tag }}
