name: build

on:
    pull_request_comment:
        types: [created]
    # issue_comment:
    #     types: [created]
    pull_request:
        types: [synchronize]

env:
    DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
    DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

jobs:
    build-odoo-community-image-17:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  ref: 17
                  fetch-depth: 1

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ env.DOCKERHUB_USERNAME }}
                  password: ${{ env.DOCKERHUB_TOKEN }}
            - name: Build & Publish image
              run: |
                  docker build -t ${{ env.DOCKERHUB_USERNAME }}/odoo:17 .
                  docker push ${{ env.DOCKERHUB_USERNAME }}/odoo:17

    build-odoo-community-image-16:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  ref: 16
                  fetch-depth: 1

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ env.DOCKERHUB_USERNAME }}
                  password: ${{ env.DOCKERHUB_TOKEN }}
            - name: Build & Publish image
              run: |
                  docker build -t ${{ env.DOCKERHUB_USERNAME }}/odoo:16 .
                  docker push ${{ env.DOCKERHUB_USERNAME }}/odoo:16

    build-odoo-community-image-15:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  ref: 15
                  fetch-depth: 1

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ env.DOCKERHUB_USERNAME }}
                  password: ${{ env.DOCKERHUB_TOKEN }}
            - name: Build & Publish image
              run: |
                  docker build -t ${{ env.DOCKERHUB_USERNAME }}/odoo:15 .
                  docker push ${{ env.DOCKERHUB_USERNAME }}/odoo:15
