name: Checkout and build image # reusable workflow

on:
    workflow_call:
        inputs:
            ref:
                required: true
                type: string
            image_tag:
                required: true
                type: string
            version_code:
                required: true
                type: string
        secrets:
            DOCKERHUB_USERNAME:
                required: true
            DOCKERHUB_TOKEN:
                required: true

jobs:
    commit-latest-release:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  ref: ${{ inputs.ref }}
                  fetch-depth: 1

            - name: Get release bash from nightly server
              run: |
                  function get_latest_release_info {
                      file_name="odoo_${odoo_version_code}.latest_amd64.changes"
                      url="https://nightly.odoo.com/${odoo_version_code}/nightly/deb/${file_name}"
                      curl -O $url

                      start_line_content="Checksums-Sha1:"
                      line_number=$(grep -n "$start_line_content" "$file_name" | awk -F ':' '{print $1}')
                      latest_release_info_line_number=$(($line_number + 3))
                      latest_release_info=$(sed -n "${latest_release_info_line_number}p" "$file_name")
                      latest_release_info=$(echo "$latest_release_info" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')
                      words=($latest_release_info)

                      declare -g release_checksum=${words[0]}
                      declare -g release_date=$(echo ${words[2]} | grep -o "[0-9]\{8\}")
                  }

                  function update_latest_release_to_dockerfile {
                      sed -i "s/^\s*ARG ODOO_RELEASE\s*.*/ARG ODOO_RELEASE=${release_date}/g" $docker_file_path
                      sed -i "s/^\s*ARG ODOO_SHA\s*.*/ARG ODOO_SHA=${release_checksum}/g" $docker_file_path
                  }

                  odoo_version_code=${{ inputs.version_code }}
                  docker_file_path=${{ github.workspace }}/Dockerfile

                  get_latest_release_info
                  update_latest_release_to_dockerfile

            - uses: stefanzweifel/git-auto-commit-action@v5
              with:
                  commit_message: Update latest release in Dockerfile

    build_and_push:
        runs-on: ubuntu-latest
        needs: [commit-latest-release]
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  ref: ${{ inputs.ref }}
                  fetch-depth: 1

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Build & Publish image
              run: |
                  docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/${{ inputs.image_tag }} .
                  docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ inputs.image_tag }}
