name: Get and commit latest Odoo release # reusable workflow

on:
    workflow_call:
        inputs:
            version_code:
                required: true
                type: string

jobs:
    commit-latest-release:
        runs-on: ubuntu-latest
        steps:
            - name: Get release bash from nightly server
              run: |
                  bash ${{ github.workspace }}/scripts/update-latest-release.sh "${{ inputs.version_code }}" "${{ github.workspace }}/Dockerfile"
