name: Get and commit latest Odoo release # reusable workflow

on:
    workflow_call:
        inputs:
            ref:
                required: true
                type: string
            version_code:
                required: true
                type: string

jobs:
    commit-latest-release:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  ref: ${{ inputs.ref }}
                  fetch-depth: 1

            - name: Get release bash from nightly server
              run: |
                  bash ${{ github.workspace }}/scripts/update-latest-release.sh "${{ inputs.version_code }}" "${{ github.workspace }}/Dockerfile"

            - uses: stefanzweifel/git-auto-commit-action@v5
              with:
                  commit_message: Update latest release in Dockerfile
